---
- name: ensure etherpad packages are installed
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
     - "{{ 'php5-cli' if ansible_distribution_major_version|int <= 8 else 'php-cli' }}"
     - "{{ 'php5-curl' if ansible_distribution_major_version|int <= 8 else 'php-curl' }}"
     - "{{ 'php5-sqlite' if ansible_distribution_major_version|int <= 8 else 'php-sqlite3' }}"

- name: ensure etherpad-lite-console is present
  git:
    repo: https://github.com/0x46616c6b/etherpad-lite-console
    dest: "{{ etherpad_console_path }}"
  become: true
  become_user: "{{ etherpad_user }}"

- name: ensure purge cronjob is latest
  cron:
    name: "etherpad-lite-console pad purge command"
    job: "{{ etherpad_console_path }}/bin/console pad:purge --apikey={{ etherpad_api_key }} --days={{ etherpad_console_purge_delay }}"
    hour: "4"
    minute: "0"
    state: "{% if etherpad_console_purge_enabled %}present{% else %}absent{% endif %}"
